# Generated by Django 5.0.6 on 2024-07-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(default='Ubicacion', max_length=255),
            preserve_default=False,
        ),
    ]
