# Generated by Django 5.0.6 on 2024-07-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='ubicacion',
            new_name='ubicación',
        ),
    ]
