# Generated by Django 5.0.6 on 2024-07-06 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_rename_ubicacion_evento_ubicación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descripcion',
            new_name='descripción',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fecha_inicio',
            new_name='fecha_de_inicio',
        ),
    ]
