# Generated by Django 5.0.6 on 2024-07-08 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_evento_creador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='ubicación',
            new_name='ubicacion',
        ),
    ]
